import { Router } from 'express';
import authRoutes from './authRoutes';
import candidateRoutes from './candidateRoutes';
import governanceRoutes from './governanceRoutes';
import interviewRoutes from './interviewRoutes';
import feedbackRoutes from './feedbackRoutes';
import offerRoutes from './offerRoutes';
import offerCreateRoutes from './offerCreateRoutes';
import approvalRoutes from './approvalRoutes';
import auditRoutes from './auditRoutes';
import userRoutes from './userRoutes';
import dashboardRoutes from './dashboardRoutes';
import draftRoutes from './draftRoutes';
import attendanceRoutes from './attendanceRoutes';
import leaveRoutes from './leaveRoutes';
import teamRoutes from './teamRoutes';
import peopleRoutes from './peopleRoutes';
import taskRoutes from './taskRoutes';
import performanceRoutes from './performanceRoutes';
import exitRoutes from './exitRoutes';
import alertsRoutes from './alertsRoutes';
import calendarRoutes from './calendarRoutes';
import knowledgeBaseRoutes from './knowledgeBaseRoutes';
import taRoutes from './taRoutes';
import jobRequisitionRoutes from './jobRequisitionRoutes';
import reportRoutes from './reportRoutes';
import pulseRoutes from './pulseRoutes';
import recognitionRoutes from './recognitionRoutes';
import announcementRoutes from './announcementRoutes';
import assessmentRoutes from './assessmentRoutes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/leave', leaveRoutes);
router.use('/team', teamRoutes);
router.use('/people', peopleRoutes);
router.use('/tasks', taskRoutes);
router.use('/performance', performanceRoutes);
router.use('/exit', exitRoutes);
router.use('/alerts', alertsRoutes);
router.use('/calendar', calendarRoutes);
router.use('/knowledge-base', knowledgeBaseRoutes);
router.use('/candidates', governanceRoutes);
router.use('/candidates', candidateRoutes);
router.use('/interviews', interviewRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/offers', offerCreateRoutes);
router.use('/offers', offerRoutes);
router.use('/approvals', approvalRoutes);
router.use('/audit', auditRoutes);
router.use('/drafts', draftRoutes);
router.use('/users', userRoutes);
router.use('/ta', taRoutes);
router.use('/job-requisitions', jobRequisitionRoutes);
router.use('/reports', reportRoutes);
router.use('/pulse', pulseRoutes);
router.use('/recognition', recognitionRoutes);
router.use('/announcements', announcementRoutes);
router.use('/assessments', assessmentRoutes);

export default router;
